### ISSUE TITLE
internal docs in `api.json`?

### ISSUE THREAD

**Issue by y-haidar** [tamasfe/aide#107]
I was playing around with aide, and trying different things, then I noticed this issue. I tried `aide = { version = "=0.13.0" ...` still the same. Though, this is not happening with the example that aide provided, my code is not that much different.

[reproducible example](https://github.com/y-haidar/aide-examples)

here is the full generated file: [api.json](https://github.com/tamasfe/aide/files/14065206/api.json)

## screen shot

![image](https://github.com/tamasfe/aide/assets/112496451/95456b6e-86e3-442e-a4de-6d9fc13496ef)

**Comment by Wicpar** [comment]
0.13.0 is bugged IIRC, see changelog, please use 0.13, 1.13.1, or 0.13.2

**Comment by y-haidar** [comment]
@Wicpar but I was using version 0.13.2

**Comment by y-haidar** [comment]
I found it. The `.into_response()` call stopped `Json` from generating docs for `OpenApi` struct. I was wrong about "internal docs"  being extracted.

My code:

```rust
async fn serve_docs(Extension(api): Extension<Arc<OpenApi>>) -> impl IntoApiResponse {
    Json(api)
}
```

Aide example:
```rust
async fn serve_docs(Extension(api): Extension<Arc<OpenApi>>) -> impl IntoApiResponse {
    Json(api).into_response()
}
```

Honestly, don't you see that there is a problem here? Yes I may be stupid, but I meant, the example/documentation is way too fragile, and bad. How am I supposed to know that `into_response()` would prevent the output from being generated?

**Comment by Wicpar** [comment]
Oh, i will investigate it, can you make a minimal example?

**Comment by y-haidar** [comment]
@Wicpar These is no problem, it was my mistake. Thank you and sorry for your time.

The code I was talking about is this:
https://github.com/tamasfe/aide/blob/6a3ca0107409797baf31f0ebf30724b39e880f7e/examples/example-axum/src/docs.rs#L56-L58

Closing.

**Comment by tamasfe** [comment]
> but I meant, the example/documentation is way too fragile, and bad. How am I supposed to know that into_response() would prevent the output from being generated?

`impl IntoApiResponse` hides the actual response type, `Json<OpenApi>` and `Response` are two different types. Axum's `Response` also implements `IntoApiResponse` but does not add any information, whereas `Json<OpenApi>` includes the schema of `OpenApi` itself like in your example.

**Comment by y-haidar** [comment]
@tamasfe exactly, such a small detail yet an important one, I spent considerable time trying to figure out what was going on. Sorry for the rant.
