### ISSUE TITLE
How to define min / max for ints/numbers Query params?

### ISSUE THREAD

**Issue by itsbalamurali** [tamasfe/aide#108]
How to define min / max for ints/numbers Query params?

**Comment by y-haidar** [comment]
As far as I have tested/read, `schemars::JsonSchema` have a `#[validate(...)]` attribute that matches `validator::Validate`, from the [validator](https://docs.rs/validator/latest/validator/) crate.

```rust
#[derive(JsonSchema)]
struct Example {
    #[validate(length(min = 5))]
    field: String,
    #[validate(range(min = 18, max = 20))]
    number: u32,
}
```

Was this what you needed?

**Comment by itsbalamurali** [comment]
Thanks @y-haidar !
