### ISSUE TITLE
Support for x-tagGroups

### ISSUE THREAD

**Issue by imran-mirza79** [tamasfe/aide#120]
How can I achieve the following
[x-tagGroups](https://redocly.com/docs/api-reference-docs/specification-extensions/x-tag-groups/)

**Comment by y-haidar** [comment]
Use `tag` method of `TransformOperation`. The example in the repo show case this.

https://github.com/tamasfe/aide/blob/6a3ca0107409797baf31f0ebf30724b39e880f7e/examples/example-axum/src/main.rs#L53-L57

Another example

```rust
fn test_fn_docs(op: TransformOperation) -> TransformOperation {
  op.description("Test fn.").tag("Test Tag")
}

let app = ApiRouter::new()
    .api_route("/api/test_fn", routing::get_with(test_fn, test_fn_docs))
   // ...
```

**Comment by imran-mirza79** [comment]
I am already using this tag method. I want group it, as highlighted in red box in the image.

Screenshot from this link: [x-tagGroups](https://redocly.com/docs/api-reference-docs/specification-extensions/x-tag-groups/)

![image](https://github.com/tamasfe/aide/assets/62472000/2679bcda-f44f-458e-8cc5-0558065400e2)

**Comment by y-haidar** [comment]
Oh it is a "group" of other tags. I could be wrong but I don't think I have seen this option in aide. I did a quick google search on this, and I think this is a `redoc` specific feature and not part of OpenAPI Specification.

**Comment by Wicpar** [comment]
you can add `x-tagGroups` like this:
```rust
use serde_json::json;
use aide::openapi::OpenApi; 

let mut api: OpenApi = ...; // get the api struct that you initialize at the start, and where you finish the api into.
api.extensions.insert("x-tagGroups", json!({
    "name": "My Group", 
    "tags": ["tag1", "tag2", "etc..."]
}));
```
