### ISSUE TITLE
Consider removing derive_more dependency

### ISSUE THREAD

**Issue by svix-jplatte** [tamasfe/aide#122]
This dependency is only used to derive trivial implementations of `AsRef`, `AsMut`, `Deref`, `DerefMut` and `From`, but it comes with a pretty significant compile time hit (3.3s on my machine, compared to aide's 4.6s). Would you accept a PR to replace those derived implementations with hand-written ones (or maybe `macro_rules!`-generated ones)?

**Comment by Wicpar** [comment]
oh i didn't know it had such an impact... hand written ones are fine, but is there no similar crate with better compile times ? Initially the idea was to remove code bloat from trivial impls.

**Comment by svix-jplatte** [comment]
I'm not aware of a similar crate with better compile times. But I also expect the hand-written impls to take no more than 100 LOC. I can also try the `macro_rules!` approach, it should reduce the boilerplate to almost the same extent as using derives.
