### ISSUE TITLE
Wasm compatibility 

### ISSUE THREAD

**Issue by domlen2003** [tamasfe/aide#129]
## Motivation
Since `axum` is now supported on cloudflare workers and direct wasm deployment on Docker and Kubernetes also gets more popular, wasm compatibility would be a huge plus for this library.

## Current Problems
It seems for some convenience features currently `aide` depends on the whole default `axum` crate? This introduces wasm compatibility problems since `axum` is only wasm compatible when excluding some features.

## Proposal
Add a feature `"wasm"` which (when disabling default features) allows to compile for wasm.

**Comment by domlen2003** [comment]
It seems fairly easy actually

**Comment by Wicpar** [comment]
released in 0.13.4
