### ISSUE TITLE
Add trailing slash removal support when axum-extra feature is enabled

### ISSUE THREAD

**Issue by Snapstromegon** [tamasfe/aide#138]
Axum-extra adds the convenient `_with_tsr()` methods to e.g. the router: https://docs.rs/axum-extra/0.9.3/axum_extra/routing/trait.RouterExt.html#tymethod.route_with_tsr

I use these quite frequently and haven't found a way to use those with the aide ApiRouter even when the axum-extra feature is enabled. Is it possible/feasable to add support for this to aide?

**Comment by tamasfe** [comment]
The [RouterExt](https://docs.rs/axum-extra/0.9.3/axum_extra/routing/trait.RouterExt.html) trait from `axum-extra` is missing from aide completely, it would be a welcome addition.
