### ISSUE TITLE
Documentation generation missing paths

### ISSUE THREAD

**Issue by HansTrashy** [tamasfe/aide#16]
Since updating aide for axum `0.6.0-rc.5` compatibility the generation of the documentation seems to be broken. Specificially the `"paths":{}` section of the generated json is empty. Testing the example in the repository reproduces the issue:

![Capture](https://user-images.githubusercontent.com/6546922/203778381-669edd47-1a6c-462a-a9e7-98ba2875e3a3.JPG)

**Comment by tamasfe** [comment]
I will look into the axum integration once it reaches `0.6.0` stable, I don't have the capacity to account for breaking changes between rc versions.

If anyone's interested in keeping the library in sync, fixes/PRs are obviously welcome!

**Comment by tamasfe** [comment]
I've just published the latest version that should be compatible with axum `0.6.0`.
