### ISSUE TITLE
Better handle jsonschema -> serde issues when converting ints

### ISSUE THREAD

**Issue by arlyon** [tamasfe/aide#17]
Hi! I am testing out this library and noticed that we don't get any error message when passing in int-like floats.

```json
{ "number": 2.9 }

{
    "error": "request schema validation failed",
    "schema_validation": [
        {
            "error": "2.3 is not of type \"integer\"",
            "instanceLocation": "/number",
            "keywordLocation": "/properties/number/type"
        }
    ]
}
```

```json
{ "number": 3.0 }

{
    "error": "invalid request"
}
```

It seems that jsonschema and serde_json differ in their definition of what a valid int looks like. Since json blurs the lines between floats and integers, the representation 3.0 passes the jsonschema validation (since 3.0 is _is_ an integer https://json-schema.org/understanding-json-schema/reference/numeric.html) despite being rejected by serde_json (https://docs.rs/serde_json/latest/src/serde_json/number.rs.html#94).

How can we handle this? At the very least we could maybe intercept and use serde_path_to_error to potentially expose the serde rejection in that case? Or potentially adjust the jsonschema to reject technically-valid json integers with a decimal.

This doesn't really fall into the domain of schemars, as it is (correctly) producing a schema that is as close to serde as possible, and jsonschema is (correctly) allowing decimal numbers with a 0 component pass, but serde is rejecting it, since its definition of an int differs from that of jsonschema. That leads us to this crate, that sits between a rock and a hard place so-to-speak, attempting to marry the three.

**Comment by tamasfe** [comment]
I have no good solution for this as I cannot change either side, the issue should be filed against `serde_json` to accept `1.0` as an integer (I wouldn't count on it) or `jsonschema` to reject integers that look like floats.

The best I can do is exposing the serde error after validation in the rejection, as you suggested.

**Comment by arlyon** [comment]
Yeah I think if possible we should try to make the error in this case as similar to the other response as possible. We can use serde_path_to_error to match the formatting, and warn that serde was not able to deserialize. I think this may be the only incompatibility between the two. I may have time to write a PR for this this weekend.

**Comment by tamasfe** [comment]
> I may have time to write a PR for this this weekend.

Thanks, much appreciated, if you have the time.
