### ISSUE TITLE
`ApiRouter` has derived `Clone` bounds on generics

### ISSUE THREAD

**Issue by cameron1024** [tamasfe/aide#19]
I'm trying out `aide`, and loving it so far. I've run into an issue using `axum_test_helper`, which exposes a test client which significantly helps when writing tests.

The issue I've run into is roughly:
 - `TestClient::new(router)` requires `router` is `Clone`
 - `ApiRouter` is not `Clone`, because the `Body` (the default for the `B` parameter) is not `Clone`, because deriving `Clone` adds a `Clone` bound on all generic parameters
 - `Router` (from `axum` itself) doesn't derive `Clone`, but has a manual impl without such requirements:
 ```rust
impl<S, B> Clone for Router<S, B> {
    fn clone(&self) -> Self {
      // ...
    }
}
```
 
I'm not familiar with the internals of `aide`, but from a brief look, it doesn't seem like this requirement is necessary (moreover, it probably *shouldn't* be if it is, since IMO an openapi generator shouldn't be intercepting actual requests and cloning them).

Would you be interested in a PR that removes this limitation?

Thanks :grin:

**Comment by tamasfe** [comment]
Thank you! The goal is to mimic axum as closely as possible. This is likely just a common gotcha with the `derive` macro.

> Would you be interested in a PR that removes this limitation?

Thanks, but I'll fix some other issues and publish a new version soon and will remove this limitation while I'm at it as well.
