### ISSUE TITLE
Support optional JSON extractors

### ISSUE THREAD

**Issue by baadc0de** [tamasfe/aide#29]
Axum allows for `Result<Json<Value>, JsonRejection>` to be passed as a variant of an [optional extractor](https://docs.rs/axum/latest/axum/extract/index.html#optional-extractors).

A handler with that kind of argument does not implement `OperationHandler`.

It would be useful to support in case the handler has its own error handling logic.

**Comment by tamasfe** [comment]
`Result` inputs now should be possible in `0.10.0`.
