### ISSUE TITLE
Add a bunch of generic tuple implementations of OperationOutput

### ISSUE THREAD

**Issue by gagbo** [tamasfe/aide#30]
Hello,

Thanks for the crate it seems to have everything we need and I'm currently testing a migration to see if everything would work fine for us.

I'd like to know if you could consider adding a lot [more tuple arities to the OperationOutput trait implementors](https://github.com/tamasfe/aide/blob/556227c330481f960e99e9ee3889cf06a09965d4/crates/aide/src/impls/mod.rs#L379), as I have a route that returns 3-tuples now, and it gets boilerplate-y to deal with those, re-adding auto-matically derived traits and having the extra (un)wrapping calls to make at usage sites:

```rust
/// This fails
static_assertions::assert_impl_all!((StatusCode, HeaderMap<HeaderValue>, StreamBody<ByteStream>): aide::operation::OperationOutput);

/// This works, but I have to add the extra new type below and change all my APIs with wrappers/into_inner calls
static_assertions::assert_impl_all!(ThreePartResponse<StatusCode, HeaderMap<HeaderValue>, StreamBody<ByteStream>: aide::operation::OperationOutput);

pub struct ThreePartResponse<T1, T2, T3>(T1, T2, T3);
impl<T1, T2, T3> axum::response::IntoResponse for ThreePartResponse<T1, T2, T3>
where
    T1: axum::response::IntoResponseParts,
    T2: axum::response::IntoResponseParts,
    T3: axum::response::IntoResponse,
{
    fn into_response(self) -> axum::response::Response {
        self.into_inner().into_response()
   }
}

impl<T1, T2, T3> aide::OperationOutput for ThreePartResponse<T1, T2, T3> {
    type Inner = std::convert::Infallible;
}
impl<T1, T2, T3> ThreePartResponse<T1, T2, T3> {
    pub fn into_inner(self) -> (T1, T2, T3) {
        (self.0, self.1, self.2)
    }
}
```

Cheers, and enjoy end of year festivities,

Gerry

**Comment by tamasfe** [comment]
Hi, thank you. Sorry about the late reply.

Sure, I'm open for PRs, anything that's valid in an `axum` handler should be also possible with `aide` in the mix. I typically use custom response types so I'm not aware of all the tuple combinations axum supports.
