### ISSUE TITLE
Feature request: Add support for TypedHeader extractor

### ISSUE THREAD

**Issue by gagbo** [tamasfe/aide#31]
There is no implementation currently of OperationInput (didn't check OperationOutput yet) for [TypedHeader](https://docs.rs/axum/latest/axum/struct.TypedHeader.html) extractor. That means we cannot use those handler in api_routes as far as I understand.

I didn't check too much the spec of OpenAPI, but if I were to make a PR for this, I would need to actually implement the optional methods of the trait so that it appears in the schema right?

**Comment by tamasfe** [comment]
Thanks, I've added this in `0.10.0` behind the `axum-headers` feature.
