### ISSUE TITLE
Merging routers containing routes with the same path but different methods

### ISSUE THREAD

**Issue by svix-andor** [tamasfe/aide#51]
If I'm reading the code correctly, then if you merge two routers, each with a route that is on the same path but listening for a different method then the second one will overwrite the specification in `paths`. I'm talking about the following: https://github.com/tamasfe/aide/blob/dcac37586ce753abf071548345777510b694d154/crates/aide/src/axum/mod.rs#L489-L502

Specifically, instead of `paths.extend(other.paths)`, the entry should be retrieved and merging should be done on the method level, so that two routers with overlapping paths but nonoverlapping methods can be merged correctly.

**Comment by Wicpar** [comment]
Just made a PR with a fix :)

**Comment by Wicpar** [comment]
fix merged in master
