### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by tamasfe** [tamasfe/aide#55]
It seems I cannot dedicate any time to OSS currently, so I'm looking for maintainers to triage/merge PRs and to publish occasional releases, so that people who rely on this library do not have to wait months for responses/fixes/features.

**Comment by Wicpar** [comment]
I'm using this crate on a pre-production project for my company, since i'll have to make PRs anyway to improve the crate i'd gladly help out on the other things too :)

**Comment by netthier** [comment]
We're also using this crate in a similar way. I don't think I have the time to be a maintainer, but I'll look into contributing back at least a bit.

**Comment by tamasfe** [comment]
Thank you @Wicpar, I have invited you as a collaborator, I think I'll have to set up CI so releases are not blocked on me, or at least grant you access on crates.io.

**Comment by Wicpar** [comment]
> Thank you @Wicpar, I have invited you as a collaborator, I think I'll have to set up CI so releases are not blocked on me, or at least grant you access on crates.io.

Thanks, i'll try to get things in order before i do any changes :)

**Comment by tasn** [comment]
Just wanted to jump in and thank @tamasfe for all your work so far, and thanks @Wicpar for taking over. I love this crate and glad to see it's still being maintained! 🙏🏻

**Comment by kaujea** [comment]
I'd love to help maintain this project! @Wicpar @tamasfe if there is anything I can do to help, please let me know.

**Comment by Wicpar** [comment]
@tamasfe if you want me to publish the changes on crates.io you can add me (Wicpar) to the owners in the crate settings.

**Comment by tamasfe** [comment]
> @tamasfe if you want me to publish the changes on crates.io you can add me (Wicpar) to the owners in the crate settings.

Sure, thank you. I've sent an invite.

**Comment by Wicpar** [comment]
@tamasfe i don't have the rights to publish updates to axum-jsonschema, i just buped the version and changelog. I did update aide to 0.12.0 though. Putting the other crates online.

**Comment by JakkuSakura** [comment]
Hi, I'd like to contribute to this nice crate as I see something inconvenient. It lays out a nice framework, though many places could be improved like in #95

**Comment by hadrien-toma** [comment]
I think I can help too :blush:, thanks for this awesome project @tamasfe :pray: :heart: !

**Comment by svix-jplatte** [comment]
Hey, it looks like once again maintenance is very slow. Are you still looking to add more maintainers @tamasfe @Wicpar?

**Comment by tamasfe** [comment]
Sorry everyone about the long inactivity, yes, help would be much appreciated here. If anyone is still interested in managing PRs and in general steering the project, I'd be happy to send invitation(s).

**Comment by svix-jplatte** [comment]
Still interested!

**Comment by JakkuSakura** [comment]
Also interested

**Comment by tasn** [comment]
@tamasfe, we maintain a fork of aide internally and would love it if we didn't have to (by having upstream be maintained). I can vouch for @svix-jplatte (he's also one of the maintainers of axum).

**Comment by tamasfe** [comment]
Thank you, I have invited @jplatte (let me know if you wish to use @svix-jplatte instead) and @JakkuSakura.
You both seem to be reasonable people so I don't think there will be any conflicts. Still, if anything arises, please ping me.

Thanks for the help again, it's much appreciated.

**Comment by jplatte** [comment]
@tamasfe thank you! How about publish rights on crates.io? The most immediate need we have from aide at work is releasing what's already merged to `main`.

**Comment by tamasfe** [comment]
Ideally a publish CD flow would be great, I have added you on crates.io as owners as well for now so you can publish the crates there, the crates are [aide](https://crates.io/crates/aide) and [aide-macros](https://crates.io/crates/aide-macros).

**Comment by JakkuSakura** [comment]
@tamasfe thank you. I accepted the invitations for the repo and crates.io

**Comment by tamasfe** [comment]
Alright, I think this issue can be closed, thanks again.
