### ISSUE TITLE
Extract Parameter from Wildcard Routes

### ISSUE THREAD

**Issue by markdingram** [tamasfe/aide#60]
From https://docs.rs/axum/latest/axum/struct.Router.html#wildcards - a route like `/assets/*path` should extract a param.

There's a good old discussion with no concrete answer at https://github.com/OAI/OpenAPI-Specification/issues/892 over precisely this should be represented in OpenAPI 3.X - from a quick scan the best approach could be to follow the AWS Gateway API style: `/assets/{path+}`

I can provide a PR?

**Comment by Wicpar** [comment]
Good idea ! We should strive to support all axum features.
