### ISSUE TITLE
Fix assembly and publication of documentation on https://docs.rs/

### ISSUE THREAD

**Issue by BogdanovAleksei** [tamasfe/aide#68]
## Fix assembly and publication of documentation on https://docs.rs/

An [error](https://docs.rs/crate/aide/0.11.0/builds/804587) occurs in the last few automated documentation builds.

The lack of documentation on https://docs.rs/ causes great discomfort during the initial acquaintance with the library.

A possible solution would be to add `default = ["axum", "axum-sqlx-tx/runtime-tokio-rustls"]` to the `[features]` section for the aide crate.

**Comment by Wicpar** [comment]
I experienced it myself, but it is undeerstandable.
The crate aims to be dependency agnostic, the best we can do is add `axum-sqlx-tx` to the docs.rs feature section. Adding these default features could also break builds.

it doesn't seem possible to activate those dependencies on the fly depending on what libraries are used, which would be the ideal solution if it was possible https://github.com/rust-lang/cargo/issues/5499

**Comment by Wicpar** [comment]
so it seems that features can be activated using for docs.rs
```
[package.metadata.docs.rs]
all-features = true
```
which is already there.

#74 fixes this definitely by removing the conflicting dependencies from the crate.

**Comment by Wicpar** [comment]
it works even without the changes :)
