### ISSUE TITLE
Return Json error with status code

### ISSUE THREAD

**Issue by IgnisDa** [tamasfe/aide#71]
Thanks for this awesome project! The examples are a bit lacking on how to work with returning errors and status code.

For example I have a handler:

```rs
#[axum::debug_handler]
pub async fn create_user(
    State(pool): State<PgPool>,
    Json(user): Json<CreateUserInput>,
) -> Result<(StatusCode, Json<CreateUserOutput>), (StatusCode, Json<CreateUserOutputError>)> {
}
```

This raises errors. I could be doing something wrong and would be glad if someone could guide me.

**Comment by Wicpar** [comment]
Can you provide the error? It's likely that your struct does not derive `JsonSchema`

**Comment by IgnisDa** [comment]
I got this working in a different way, thanks for responding.
