### ISSUE TITLE
Reduce constrain on `bytes` dependency

### ISSUE THREAD

**Issue by xgroleau** [tamasfe/aide#9]
Currently the `bytes` dependency is fixed to exactly `1.2.1` when there is no actual reason for it. Using another library with a hard requirement like [octocrab](https://github.com/XAMPPRocky/octocrab) causes a conflict between the two versions. Since the library only implements a trait, the version requirement could be looser.

**Comment by BBaoVanC** [comment]
Do you mean in Cargo.toml where it says this?

```toml
bytes = { version = "1.2.1", optional = true }
```

[According to Cargo docs][cargo-dep-docs], this doesn't lock it to exactly `1.2.1`, it lets it pick anything >= 1.2.1, but less than 2.0.0

[cargo-dep-docs]: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html

**Comment by tamasfe** [comment]
Even if it doesn't conflict with that particular library, a library with a requirement of `=1.2.0` would be enough to cause a conflict.

This has been brought up before, it's a reasonable request, we should loosen all dependency versions as much as possible.

**Comment by tamasfe** [comment]
The newest version has much looser dependency requirements.
